version: '3.8'
services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  acebook:
    image: 664047078509.dkr.ecr.eu-west-2.amazonaws.com/acebook-lina-jay-grace_repo:prod
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URL=mongodb://mongo:27017/acebook
    restart: unless-stopped

volumes:
  mongo-data:

